update Readme
oSoc17/code9000 pull request #182
Opened 2017-07-17 20:54 UTC by BertCommeine

close #74

2017-07-18 05:55 UTC, DemianD requested changes
At this moment we never explain to the user wich technology we are using (Laravel, ReactJS)?

Also, I guess we discussed last week to use different README files. Their are also issues for that made, see #73 #74 #75 

Will make things clear.

Also, at the general README we can put our logo and some badges from Travis to indicate that our build is success. 

Even list up the contributors and the sponsors (Mobile Vikins, ...)

2017-07-18 05:55 UTC, DemianD commented on README.md
> +\#Code9000 is a project in which Digipolis Ghent and the City of Ghent experiment with open data to create new open source proof-of-concepts. We’ve been doing this since 2011 and love to work with te
Change IOT -> IoT

2017-07-18 05:55 UTC, DemianD commented on README.md
> +####  Requirements
The requirements are shuffled per project. Like PHP, Composer and Mysql is for the API

Also, do we only need python for the Hardware side? I guess we'll need more like the Raspian. CC @DylanVanAssche

2017-07-18 05:55 UTC, DemianD commented on README.md
> +##### 1. Webapplicatie
Please use your Dunglish skills

2017-07-18 05:55 UTC, DemianD commented on README.md
> +Copy .env.example to .env, and change the URL to the one of your API. This will probably be a localhost:// + the port where you run the API.
I won't say it'll be a localhost. Most devs are running their virtual hosts

2017-07-18 05:55 UTC, DemianD commented on README.md
> +$  yarn watch css
It's yarn watch-css.
But I'll change this later when you do yarn start, it automatically starts the watch-css

2017-07-18 05:55 UTC, DemianD commented on README.md
> +$ php artisan key:generate
```php artisan key:generate```is not for your database. It is for your environment file

2017-07-18 15:37 UTC, DemianD commented on README.md
> +We made a reactjs webapp where you can do all the account-related stuff like logging in or making an account. We made an voting page as well, and tried to implement fun features like scores, badges a
ReactJS *

2017-07-18 18:21 UTC, DemianD reviewed
For me this is okay. Maybe we can add a hyperlink to osoc and digipolis so they can click on it?

Otherwise, @DylanVanAssche you need to do your magic. 

Maybe someone needs to read is for grammar?

2017-07-20 07:23 UTC, DylanVanAssche commented
@DemianD changes OK?

2017-07-20 09:46 UTC, DemianD commented
@DylanVanAssche , @BertCommeine I approve ! 👍  👍

2017-07-20 09:46 UTC, DemianD approved these changes

2017-07-20 10:03 UTC, merged