Feature/issue 59
oSoc17/code9000 pull request #278
Opened 2017-07-24 18:25 UTC by BertCommeine

close #59

2017-07-24 18:36 UTC, BertCommeine commented
Did something wrong while solving a merge conflict, just let me take care of it

2017-07-24 19:59 UTC, DemianD commented
@BertCommeine If you need help, ping me

2017-07-24 21:02 UTC, DemianD commented on web-app/src/components/Polaroid/Polaroid.scss
> +}
There are all fallback for browser, but there's one that doesn't fit in this list: ```-webkit-user-drag: none;```
Also, I guess that the fallbacks are auto generated by sass (correct me if 'm wrong)

2017-07-24 21:03 UTC, DemianD requested changes
Except of that one nitpick, the code looks good! 👍

2017-07-24 21:03 UTC, DemianD commented on web-app/src/components/Polaroid/Polaroid.scss
> +    -webkit-user-drag: none;
There are all fallback for browser, but there's one that doesn't fit in this list: ```-webkit-user-drag: none;```
Also, I guess that the fallbacks are auto generated by sass (correct me if 'm wrong)

2017-07-25 07:48 UTC, DemianD requested changes

2017-07-25 07:48 UTC, DemianD commented on web-app/src/components/Observations/Observations.js
> +                onSwipeLeft={() => vote(1)}
Left is -1

2017-07-25 12:59 UTC, DemianD requested changes

2017-07-25 12:59 UTC, DemianD commented on web-app/package.json
> +    "react-draggable": "^2.2.6",
We are not using this

2017-07-25 12:59 UTC, DemianD commented on web-app/package.json
> +    "react-touch": "^0.4.2",
We are not using this

2017-07-25 14:43 UTC, merged